using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace DiceGame1
{
    public partial class GameWindow : Window
    {
        private GameManager _game;
        private List<IModifier> _modifierPool;
        private List<IModifier> _currentChoices;
        private IModifier _selectedModifier;
        private Random _rng = new Random();

        private enum GameState { BeforeProto, AwaitRoll, AwaitCreateClones, GameOver }
        private GameState _state = GameState.BeforeProto;

        public GameWindow()
        {
            InitializeComponent();
            _game = new GameManager();
            _modifierPool = ModifierPool.All();
            TxtBest.Text = $"Лучший: {_game.BestScore}";

            // Show target 1 now (generated by GameManager ctor / GetOrCreateTarget)
            UpdatePreviewBeforeProto();

            TxtFaces.TextChanged += TxtFaces_TextChanged;
            UpdateUI_State();
        }

        private void TxtFaces_TextChanged(object sender, TextChangedEventArgs e)
        {
            // do not recompute target from faces — preview is generated by manager
            if (_state == GameState.BeforeProto) UpdatePreviewBeforeProto();
        }

        private void UpdatePreviewBeforeProto()
        {
            var t = _game.GetTargetForRound(1);
            int pts = _game.GetPointsForRound(1);
            TxtTarget.Text = $"Цель (предпросмотр): {t.Min} - {t.Max} (очков: {pts})";
        }

        private void UpdateUI_State()
        {
            switch (_state)
            {
                case GameState.BeforeProto:
                    CmbMods.Visibility = Visibility.Collapsed;
                    TxtModDescription.Visibility = Visibility.Collapsed;
                    BtnCreateClones.Visibility = Visibility.Collapsed;
                    BtnRollAll.Visibility = Visibility.Collapsed;
                    BtnCreateProto.IsEnabled = true;
                    BtnCreateProto.Visibility = Visibility.Visible;
                    BtnNewGame.IsEnabled = true;
                    UpdatePreviewBeforeProto();
                    break;

                case GameState.AwaitRoll:
                    var cur = _game.GetTargetForRound(_game.RoundNumber);
                    TxtTarget.Text = $"Цель: {cur.Min} - {cur.Max} (очков: {_game.GetPointsForRound(_game.RoundNumber)})";
                    CmbMods.Visibility = Visibility.Collapsed;
                    TxtModDescription.Visibility = Visibility.Collapsed;
                    BtnCreateClones.Visibility = Visibility.Collapsed;
                    BtnRollAll.Visibility = Visibility.Visible;
                    BtnCreateProto.IsEnabled = false;
                    break;

                case GameState.AwaitCreateClones:
                    var next = _game.GetTargetForRound(_game.RoundNumber + 1);
                    int nextPts = _game.GetPointsForRound(_game.RoundNumber + 1);
                    TxtTarget.Text = $"Следующий раунд — цель: {next.Min} - {next.Max} (очков: {nextPts})";
                    PopulateRandomModifiersChoices();
                    CmbMods.Visibility = Visibility.Visible;
                    TxtModDescription.Visibility = Visibility.Visible;
                    BtnCreateClones.Visibility = Visibility.Visible;
                    BtnRollAll.Visibility = Visibility.Collapsed;
                    BtnCreateProto.IsEnabled = false;
                    break;

                case GameState.GameOver:
                    CmbMods.Visibility = Visibility.Collapsed;
                    TxtModDescription.Visibility = Visibility.Collapsed;
                    BtnCreateClones.Visibility = Visibility.Collapsed;
                    BtnRollAll.Visibility = Visibility.Collapsed;
                    BtnCreateProto.Visibility = Visibility.Collapsed;
                    BtnCreateProto.IsEnabled = false;
                    BtnNewGame.IsEnabled = true;
                    TxtTarget.Text = "Цель: —";
                    break;
            }

            TxtScore.Text = $"Очки: {_game.Score}";
            TxtRound.Text = _game.OriginalPrototype == null ? "Раунд: -" : $"Раунд: {_game.RoundNumber}";
            RefreshDiceDisplay();
        }

        private void RefreshDiceDisplay()
        {
            DicePanel.Children.Clear();
            if (_game.AllDice == null) return;
            foreach (var d in _game.AllDice)
            {
                var br = new Border
                {
                    BorderBrush = Brushes.Gray,
                    BorderThickness = new Thickness(1),
                    CornerRadius = new CornerRadius(6),
                    Padding = new Thickness(8),
                    Margin = new Thickness(6),
                    Width = 150
                };
                var sp = new StackPanel();
                // show user-provided name for original (or "Оригинал"), and clones already have their full names
                var titleText = string.IsNullOrWhiteSpace(d.Name) ? "(без имени)" : d.Name;
                var title = new TextBlock { Text = titleText, FontWeight = FontWeights.Bold };
                var facesWrap = new WrapPanel { Margin = new Thickness(0, 6, 0, 0) };

                var faces = d.Faces ?? new List<int> { 1, 2, 3, 4, 5, 6 };
                if (faces.Count != 6)
                {
                    faces = faces.Take(6).ToList();
                    while (faces.Count < 6) faces.Add(1);
                }
                foreach (var f in faces)
                {
                    var tb = new TextBlock
                    {
                        Text = f.ToString(),
                        Width = 20,
                        TextAlignment = TextAlignment.Center,
                        Margin = new Thickness(2),
                        Background = Brushes.WhiteSmoke,
                        Padding = new Thickness(2)
                    };
                    facesWrap.Children.Add(tb);
                }
                var last = new TextBlock { Text = $"Последний бросок: {(d.LastRoll.HasValue ? d.LastRoll.Value.ToString() : "-")}", Margin = new Thickness(0, 6, 0, 0) };
                sp.Children.Add(title);
                sp.Children.Add(facesWrap);
                sp.Children.Add(last);
                br.Child = sp;
                DicePanel.Children.Add(br);
            }
        }

        private void PopulateRandomModifiersChoices()
        {
            _currentChoices = new List<IModifier>();
            var pool = new List<IModifier>(_modifierPool);
            int count = Math.Min(3, pool.Count);
            for (int i = 0; i < count; i++)
            {
                int idx = _rng.Next(pool.Count);
                _currentChoices.Add(pool[idx]);
                pool.RemoveAt(idx);
            }
            CmbMods.ItemsSource = _currentChoices.Select(m => m.Name).ToList();
            if (_currentChoices.Count > 0)
            {
                CmbMods.SelectedIndex = 0;
                _selectedModifier = _currentChoices[0];
                TxtModDescription.Text = _selectedModifier.Description;
            }
        }

        // Handlers
        private void BtnMenu_Click(object sender, RoutedEventArgs e)
        {
            var mw = new MainWindow();
            mw.Show();
            this.Close();
        }

        private void BtnNewGame_Click(object sender, RoutedEventArgs e)
        {
            _game = new GameManager();
            _modifierPool = ModifierPool.All();
            _currentChoices = null;
            _selectedModifier = null;
            _state = GameState.BeforeProto;
            TxtLog.Text = "Новая игра — создана новая цель первого раунда. Создайте прототип.";
            TxtBest.Text = $"Лучший: {_game.BestScore}";
            UpdateUI_State();
            UpdatePreviewBeforeProto();
        }

        private void BtnEnd_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show($"Игра окончена.\nВаш счёт: {_game.Score}\nЛучший: {_game.BestScore}", "Игра окончена");
            var mw = new MainWindow();
            mw.Show();
            this.Close();
        }

        private void BtnCreateProto_Click(object sender, RoutedEventArgs e)
        {
            var faces = ParseFacesStrict(TxtFaces.Text);
            if (faces == null)
            {
                MessageBox.Show("Введите ровно 6 целых чисел 1..6 через запятую.", "Ошибка");
                return;
            }

            string nameInput = string.IsNullOrWhiteSpace(TxtProtoName.Text) ? "Оригинал" : TxtProtoName.Text.Trim();
            var proto = new Dice(nameInput, faces);

            _game.SetOriginalPrototype(proto);

            // do NOT regenerate round1 target — it was created earlier and is preserved
            var t = _game.GetTargetForRound(1);
            int pts = _game.GetPointsForRound(1);
            TxtTarget.Text = $"Цель: {t.Min} - {t.Max} (очков: {pts})";

            TxtLog.Text = $"Прототип '{_game.OriginalPrototype.Name}' создан: {string.Join(",", _game.OriginalPrototype.Faces)}";
            _state = GameState.AwaitRoll;
            UpdateUI_State();
        }

        private List<int> ParseFacesStrict(string text)
        {
            if (string.IsNullOrWhiteSpace(text)) return null;
            var parts = text.Split(new[] { ',', ';' }, StringSplitOptions.RemoveEmptyEntries);
            var list = new List<int>();
            foreach (var p in parts)
            {
                if (!int.TryParse(p.Trim(), out int v)) return null;
                if (v < 1 || v > 6) return null;
                list.Add(v);
            }
            if (list.Count != 6) return null;
            return list;
        }

        private void CmbMods_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            int idx = CmbMods.SelectedIndex;
            if (_currentChoices != null && idx >= 0 && idx < _currentChoices.Count)
            {
                _selectedModifier = _currentChoices[idx];
                TxtModDescription.Text = _selectedModifier.Description;
            }
        }

        private void BtnRollAll_Click(object sender, RoutedEventArgs e)
        {
            if (_state != GameState.AwaitRoll) return;
            if (_game.AllDice == null || !_game.AllDice.Any())
            {
                MessageBox.Show("Нет кубиков. Создайте прототип.", "Ошибка");
                return;
            }

            var res = _game.ExecuteRound();
            TxtRoundResult.Text = $"Раунд {res.RoundNumber}. Сумма: {res.SumOfRolls}. Успех: {res.Success}. Очки +{res.PointsGained}.";
            TxtLog.Text = $"Брошено {_game.AllDice.Count} кубиков. Сумма: {res.SumOfRolls}.";

            if (!res.Success)
            {
                TxtLog.Text += " Попадание не произошло — игра окончена.";
                _state = GameState.GameOver;
                TxtBest.Text = $"Лучший: {_game.BestScore}";
                UpdateUI_State();
                return;
            }

            // success -> preview next round target (do NOT create clones yet)
            var nextTarget = _game.GetTargetForRound(_game.RoundNumber + 1);
            int nextPts = _game.GetPointsForRound(_game.RoundNumber + 1);
            TxtTarget.Text = $"Следующий раунд — цель: {nextTarget.Min} - {nextTarget.Max} (очков: {nextPts})";

            _state = GameState.AwaitCreateClones;
            UpdateUI_State();
        }

        private void BtnCreateClones_Click(object sender, RoutedEventArgs e)
        {
            if (_state != GameState.AwaitCreateClones) return;
            if (_game.OriginalPrototype == null) { MessageBox.Show("Сначала прототип.", "Ошибка"); return; }
            if (_selectedModifier == null) { MessageBox.Show("Выберите модификатор.", "Ошибка"); return; }

            int created = _game.CreateNextRoundClones(_selectedModifier);
            var cur = _game.GetTargetForRound(_game.RoundNumber);
            int curPts = _game.GetPointsForRound(_game.RoundNumber);
            TxtLog.Text = $"Создано {created} новых клонов для раунда {_game.RoundNumber}. Модификатор: {_selectedModifier.Name}. Текущая цель: {cur.Min}-{cur.Max} (очков: {curPts})";

            _state = GameState.AwaitRoll;
            UpdateUI_State();
        }
    }
}